networks: 
  testlink:
    name: testlink

services:
  maildev:
    image: maildev/maildev:latest
    networks:
    - testlink
    ports:
    - 1080:1080
    - 1025:1025
    restart: unless-stopped
    environment:
    - NODE_TLS_REJECT_UNAUTHORIZED:0

  app:
    build: .
    restart: unless-stopped
    depends_on:
      maildev:
        condition: service_started
    networks:
    - testlink
    ports:
    - 8090:80
    volumes:
      - ./logs:/var/testlink/logs:Z
      - ./upload_area:/var/testlink/upload_area:Z
    # --- VARIABLES DE ENTORNO PARA CONECTAR A POSTGRESQL EN RENDER ---
    environment:
      - TESTLINK_DB_TYPE=postgres
      - TESTLINK_DB_HOST=dpg-d3dkatogjchc73akcii0-a.oregon-postgres.render.com
      - TESTLINK_DB_PORT=5432
      - TESTLINK_DB_USER=teslink_user
      - TESTLINK_DB_PASSWORD=2VYR09sytPPXl3Dl08QUK1tHfaw6sLXc
      - TESTLINK_DB_NAME=teslink
      - TESTLINK_SMTP_HOST=maildev

# Se eliminaron los servicios 'db' y 'restore', y el volumen 'mysql'.